# This file is designed to implement AirFlow in a Docker container
# (rather than an EC2) for the following video
# https://youtu.be/o88LNQDH2uI?si=pTlCMx16Y9zbk-Ls
# This is the list of commands
# https://robust-dinosaur-2ef.notion.site/Running-Airflow-on-a-small-AWS-EC2-Instance-8e2a42d2ce7946c3a3d753abc13f2e57
# This is the ChatGPT convo used to update commands for Ubuntu/Docker
# https://chatgpt.com/c/66e71972-6b20-8009-8d05-bc6f96a6efae

# While the below sequence of commented commands suceed in installing Airflow
# They should be de-duplicated and cleaned up, and ulitmately made into a proper Dockerfile

# Use Ubuntu as the base image
FROM ubuntu:latest

# Update the package list and install some basic utilities (optional)
RUN apt-get update && apt-get install -y \
    bash \
    curl \
    vim && \
    rm -rf /var/lib/apt/lists/* && \
    apt update && \
    apt install python3-pip -y && \
    apt-get install software-properties-common -y && \
    add-apt-repository ppa:deadsnakes/ppa -y && \
    apt install python3.10-full -y && \
    apt-get install libpq-dev -y && \
    apt install sqlite3 && \
    /bin/python3.10 -m venv /venv && \
    source venv/bin/activate && \
    apt install -y libpq-dev build-essential && \
    apt install python3.10-dev -y && \
    pip install "apache-airflow[postgres]==2.5.0" --constraint "https://raw.githubusercontent.com/apache/airflow/constraints-2.5.0/constraints-3.7.txt" && \
    airflow db init

# Set the default command to start a bash shell
CMD ["bash"]

# Command to build the container
# docker build -f Dockerfile-ubuntu-airflow -t ubuntu-airflow .
# Command to run the container
# docker run -it ubuntu-
# Command to reconnect to the container
# docker exect -it <container-id> bash
# Command to change root password for container
# docker exec -itu root <container-id> passwd
# Commands to preserve container changes
# Open a new terminal, get the container ID: docker ps
# Commit the container as a new image:docker commit <container_id> airflow-practice

# Commands to run within bash
#    apt-get install sudo
# sudo apt-get install wget ca-certificates
#    wget --quiet -O - https://www.postgresql.org/media/keys/ACCC4CF8.asc | sudo apt-key add -
#   sudo sh -c 'echo "deb http://apt.postgresql.org/pub/repos/apt/ `lsb_release -cs`-pgdg main" >> /etc/apt/sources.list.d/pgdg.list'
# apt-get install postgresql postgresql-contrib
# su - postgres -c "/usr/lib/postgresql/16/bin/initdb -D /var/lib/postgresql/13/main"
# su - postgres -c "pg_ctlcluster 16 main start"

# sudo -i -u postgres
# psql
# CREATE DATABASE airflow;
# CREATE USER airflow WITH PASSWORD 'airflow';
# GRANT ALL PRIVILEGES ON DATABASE airflow TO airflow;
# GRANT USAGE ON SCHEMA public TO airflow;
# GRANT CREATE ON SCHEMA public TO airflow;
# GRANT ALL PRIVILEGES ON SCHEMA public TO airflow;
# ALTER USER airflow WITH SUPERUSER;


# sed -i 's#sqlite:////home/ubuntu/airflow/airflow.db#postgresql+psycopg2://airflow:airflow@localhost/airflow#g' airflow.cfg
# sed -i 's#SequentialExecutor#LocalExecutor#g' airflow.cfg

# airflow db init
# airflow users create -u airflow -f airflow -l airflow -r Admin -e airflow@gmail.com
# airflow webserver &
# airflow scheduler

# Optional
# su - postgres -c "psql -U postgres -d airflow -c \"ALTER USER airflow WITH NOSUPERUSER;\""
